spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb


app:
  auth:
    tokenSecret: apple
    tokenExpiredDate: 864000000 # 10일
    tokenPrefix: Bearer
    headerString: Authorization
